#include<iostream>
#include<cstdlib>
#include<ctime>
using namespace std;
int main()
{
	int n;
	char ans;
    srand(static_cast<unsigned int>(time(NULL)));
	int random = rand() % 10 + 1;
	cout<<"\t\t\tWelcome to Number Predictor Program\n"<<endl;
	do{
	cout<<"Enter a Number between 1 to 10:"<<endl;
	cin>>n;
	cout<<"Number generated by Computer is: "<<endl;
	cout<<random<<endl;
	if(n==random)
	{
		cout<<"Correct Answer!"<<endl;
	}
	else if(n > random)
	{
		cout<<"Your guess was more by "<<n-random<<" digits!"<<endl;
	}
	else if(random > n)
	{
		cout<<"Your guess was less by "<<random-n<<" digits"<<endl;
	}
	cout<<"\nDo you want to play more?(y/n)"<<endl;
	cin>>ans;
	}while(ans == 'y' || ans == 'Y');
	return 0;
}
